vich_uploader:
    db_driver: orm
    storage: file_system

    mappings:
        uploaded_files:
            uri_prefix: /images/uploads
            upload_destination: '%kernel.project_dir%/public/images/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer