homepage:
  path: /
  controller: App\Controller\HomeController::homepage

analyse:
  path: /analyse
  controller: App\Controller\MainController::image_stack

visualize:
  path: /visualize/{token}
  controller: App\Controller\MainController::visualize

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: GET

ajax_check_state:
    path: /ajax-check-state
    controller: App\Controller\MainController::ajax_check_state
    methods: [POST]