index:
  path: /
  controller: App\Controller\MainController::index

upload:
  path: /upload
  controller: App\Controller\FormController::new
stack:
  path: /stack
  controller: App\Controller\FormController::image_stack
show:
  path: /show/{id}
  controller: App\Controller\MainController::show