#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

homepage:
    path: /
    controller: App\Controller\HomeController::homepage

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: GET

add_user:
    path: /admin/add_user
    controller: App\Controller\SecurityController::add_user

delete_user:
    path: /admin/delete_user
    controller: App\Controller\SecurityController::delete_user