index:
  path: /
  controller: App\Controller\MainController::index

upload:
  path: /upload
  controller: App\Controller\MainController::upload
  methods: GET

upload_files:
  path: /upload
  controller: App\Controller\MainController::files
  methods: POST