homepage:
  path: /
  controller: App\Controller\HomeController::homepage

analyse:
  path: /analyze
  controller: App\Controller\MainController::image_stack

visualize:
  path: /analyze/visualize/{token}
  controller: App\Controller\MainController::visualize

uploaded:
  path: /analyze/uploaded/{token}
  controller: App\Controller\MainController::uploaded

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: GET

profil:
  path: /profil
  controller: App\Controller\SecurityController::profil
add_user:
    path: /admin/add_user
    controller: App\Controller\SecurityController::add_user
profil:
  path: /profil
  controller: App\Controller\SecurityController::profil

update_password_profil:
  path: /update
  controller: App\Controller\SecurityController::update_password_profil
  methods: [POST]
delete_user:
    path: /admin/delete_user
    controller: App\Controller\SecurityController::delete_user

ajax_check_state:
    path: /ajax-check-state
    controller: App\Controller\MainController::ajax_check_state
    methods: [POST]
ajax_start_processing:
    path: /ajax-start-processing
    controller: App\Controller\MainController::ajax_start_processing
    methods: [POST]